mode = "dark"

accent = "#7e8468"
selection = "#312e29"
muted = "#605e58"

background = "#0a0703"
dark_background = "#080502"
darker_background = "#050402"
lighter_background = "#23201c"

foreground = "#DBD0BC"
dark_foreground = "#a49c8d"
light_foreground = "#e0d7c6"
bright_foreground = "#e4dccd"

red = "#a2947d"
yellow = "#fef2cb"
orange = "#b0a491"
green = "#cbc3a3"
cyan = "#dfddb2"
blue = "#7e8468"
magenta = "#c0a78c"
brown = "#6a6257"

bright_red = "#bba98d"
bright_yellow = "#fff1c1"
bright_green = "#e4dab0"
bright_cyan = "#f7f5c0"
bright_blue = "#939978"
bright_magenta = "#dcbc99"
