# Background and foreground colors
background = #0a0703
foreground = #DBD0BC

# Standard colors
palette = 0=#0a0703
palette = 1=#a2947d
palette = 2=#cbc3a3
palette = 3=#fef2cb
palette = 4=#7e8468
palette = 5=#c0a78c
palette = 6=#dfddb2
palette = 7=#DBD0BC

# Bright colors
palette = 8=#605e58
palette = 9=#bba98d
palette = 10=#e4dab0
palette = 11=#fff1c1
palette = 12=#939978
palette = 13=#dcbc99
palette = 14=#f7f5c0
palette = 15=#f9f5ea
