$color = rgba(10, 7, 3, 1)
$inner_color = rgba(10, 7, 3, 0.66)
$outer_color = rgba(192, 167, 140, 1)
$font_color = rgba(219, 208, 188, 1)
$placeholder_color = rgba(219, 208, 188, 0.7)
$check_color = rgba(223, 221, 178, 1)
