background            #0a0703
foreground            #DBD0BC

# black
color0  #0a0703
color8  #605e58

# red
color1  #a2947d
color9  #bba98d

# green
color2  #cbc3a3
color10 #e4dab0

# yellow
color3  #fef2cb
color11 #fff1c1

# blue
color4  #7e8468
color12 #939978

# magenta
color5  #c0a78c
color13 #dcbc99

#cyan
color6  #dfddb2
color14 #f7f5c0

#white
color7  #DBD0BC
color15 #f9f5ea


